### ISSUE TITLE
`INSERT BEFORE/AFTER` support

### ISSUE THREAD

**Issue by cr1901** [pftbest/ldparser#3]
This crate has been incredibly useful for testing linker script fragments. Unfortunately, I seem to have run into some [limitations](https://github.com/cr1901/postcard-infomem/blob/main/host/src/ldscript.rs#L251).

Is it possible to `INSERT BEFORE/AFTER` functionality, so that I can test for equality against this crate's types instead of strings?

**Comment by pftbest** [comment]
Do you need INSERT command only? Or you need OVERLAY command too?

**Comment by cr1901** [comment]
@pftbest I don't need the `OVERLAY` command (and wouldn't actually know how to use it in an actual linker script). Thanks for the prompt response!
