### ISSUE TITLE
Upgrade to `nom` 7.1.3

### ISSUE THREAD

**Issue by VoodooChild99** [pftbest/ldparser#5]
Hi,

I find this crate very helpful. However, this crate is using a somewhat outdated version of `nom`. If you run `cargo fix`, you will see a warning:
```
warning: the following packages contain code that will be rejected by a future version of Rust: nom v3.2.1
```
Therefore I have managed to upgrade the `nom` version used in this crate to 7.1.3, which is the latest version. I have passes all the tests and checked that the parser generates the same output. You can checkout my fork here: https://github.com/VoodooChild99/ldparser/tree/upgrade-nom. I can open a PR if you are interested.

**Comment by pftbest** [comment]
Hello! PRs are welcome. I can also push the updated version to crates.io

**Comment by pftbest** [comment]
We can also make a breaking change to support parsing the expressions in memory regions, like the one from issue #2

**Comment by VoodooChild99** [comment]
I have opened a PR  (#6) :)

> Hello! PRs are welcome. I can also push the updated version to crates.io



Yeah, supporting evaluating expressions is challenging, I guess we'll have to evaluate every symbols (e.g., .end - .start).

> We can also make a breaking change to support parsing the expressions in memory regions, like the one from issue #2

**Comment by VoodooChild99** [comment]
Sorry, I misclicked :(

**Comment by pftbest** [comment]
Thanks, I will upload to crates.io later today

**Comment by pftbest** [comment]
@VoodooChild99  I pushed version 0.3 on crates.io. It also runs 10% faster on my PC, very nice!
